### ISSUE TITLE
question: how to generate a CITATION.cff file from a Bibtex entry?

### ISSUE THREAD

**Issue by monperrus** [citation-file-format/cff-converter-python#123]
Hi,

I'd like to generate a CITATION.cff file from a Bibtex entry.

How to do this?

Thanks!

--Martin

**Comment by jspaaks** [comment]
Hi Martin, thanks for you issue. Currently, generating CFF from bibtex is not supported by ``cffconvert`` (the flow of information is the other way around). I take it you have many such bibtex entries? If not, generate the CFF by filling in the form at https://citation-file-format.github.io/cff-initializer-javascript/

If you already have correct metadata on Zenodo for a given entry, I believe the sibling repo [``doi2cff``](https://github.com/citation-file-format/doi2cff) can help although I haven't used it in a long time, so not entirely sure.

**Comment by monperrus** [comment]
Thanks a lot for your fast answer.
