### ISSUE TITLE
APA format support

### ISSUE THREAD

**Issue by ziyangczi** [citation-file-format/cff-converter-python#157]
I wonder if it is on the roadmap to add support for APA format transform, identical to what the ruby library is currently supporting? https://github.com/citation-file-format/ruby-cff/blob/main/lib/cff/formatter/apa_formatter.rb 

If not I can help translating from ruby to python to add hopefully identical logic as current ruby-cff package

**Comment by jspaaks** [comment]
Hi @ziyangczi and welcome to the project! There is some as yet unreleased support for APA, I hope to make a release within the next couple of weeks if I can find the time.
