### ISSUE TITLE
Support conversion to markdown for landing pages

### ISSUE THREAD

**Issue by agbeltran** [citation-file-format/cff-converter-python#159]
CFF covers the information required in DOI landing pages (https://support.datacite.org/docs/landing-pages) and it would be good to have a converter from CFF to markdown than then can be hosted in e.g. Github pages (or otherwise a conversion to HTML).

Would this be helpful for users of this package?

cc @rebeccafair

**Comment by rebeccafair** [comment]
For developers who aren't using Zenodo to get their DOIs, being able to generate landing page markdown content automatically from a CITATION.cff file would be quite helpful. (And it probably doesn't belong in this repo, but some tutorials/templates for using Github pages for DOI landing pages would be nice too).

In my case to use Github pages as a landing page site I half followed [this tutorial](https://www.software.ac.uk/resources/guides/adding-schema-dot-org) using schema.org generated with cff-converter and then created my own Jekyll include HTML file to add the landing page content using the metadata: https://github.com/pace-neutrons/Euphonic/blob/gh-pages/_includes/base.html. It ended up being quite a convoluted process, surely there are others who will want to do a similar thing?

Unless I really have overcomplicated everything and there is an easier way of doing this :)

**Comment by jspaaks** [comment]
Hi @agbeltran, @rebeccafair and thanks for your interest in cffconvert.

I think the conversion to Markdown pages is (just) outside of the scope of the converter --in my mind it should convert to other file formats if need be, but a Jekyll file tree is a bit more complicated than that.

Landing pages with human and machine readable data can already be constructed using the existing infrastructure. I've created 
https://github.com/jspaaks/jekyll-metadata-test as a minimal example. You can see the metadata being recognized here https://validator.schema.org/#url=https%3A%2F%2Fjspaaks.github.io%2Fjekyll-metadata-test%2F

Some key points are:

1. make your `CITATION.cff`, convert it to schema.org formatted json data using `cffconvert -f schema.org`
2. Put the generated text in a new file `_data/metadata.json` (You may need to create the directory). The data will become available as a variable as `site.data.<filename>`, so for my example that is `site.data.metadata`
3. Look what layout your `index.markdown` is using. Mine says `layout: default`
4. Make a new file `_layouts/default.html` (You may need to create the directory). See docs for information on how to override theme files. I just made an empty html file, like so

    ```html
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>{{ site.data.metadata.name }}</title>
        <script type="application/ld+json" >
          {{ site.data.metadata | jsonify }}
        </script>
      </head>
      <body>
        {{ content }}
      </body>
    </html>
    ```

    The `script` tag is where the metadata goes; the `content` is what your `index.markdown` file supplies below the dashes; the squiggly braces are there to tell Jekyll to replace that part of the file with the value of the variable

Let me know if this works for you! Best regards, 
Jurriaan

**Comment by rebeccafair** [comment]
Thanks for your reply! It's good to hear that I have followed a similar approach to the one that you suggested. The main issue for me was creating the `content` from the metadata, I had to create the page content by getting the information from the metadata myself (e.g. https://github.com/pace-neutrons/Euphonic/blob/gh-pages/_includes/base.html). If there was a way of creating the markdown/html content directly from the CITATION.cff that would have made things easier, but I realise then there's a possibility for inconsistency between the metadata and content, and it may be hard to create markdown/html content that suits everyone. I've worked around it now and am happy with the result so you can probably close this issue :) Hopefully this thread will be useful to anyone looking to do something similar.
