### ISSUE TITLE
Move/fork to citation-file-format org?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/cff-converter-python#20]
I'm wondering if you'd be interested in moving the project to the https://github.com/citation-file-format/ organization, or have it forked and maintain the project there? This would help centralizing efforts around CFF I think, and foster re-use, etc.

**Comment by jspaaks** [comment]
seem like a good idea indeed, I'll see if I can move the repo to citation-file-format (prolly next week).

**Comment by sdruskat** [comment]
Ace, I'll add you as a member. Move whenever you can find the time, no pressure :).

Would you consider renaming it a bit as well? We have different technologies involved in the org (Java, Ruby incoming) and I think it'd be nice to have a telling name. Thinking along the lines of `cff-converter-python` or something. Entirely up to you of course.

Will you or anyone from your team be at CW18 by any chance?

**Comment by jspaaks** [comment]
repo has been transferred, but I no longer have rights to change the repo name or description... d'oh!

**Comment by jspaaks** [comment]
Hi @sdruskat,
just a gentle reminder that I don't have rights to change the repo's name according to your suggestion.

**Comment by sdruskat** [comment]
Hi @jspaaks, gave you Admin rights to the repo which should hopefully fix it. Thanks!

**Comment by jspaaks** [comment]
Done, issue can be closed AFAIC.

**Comment by sdruskat** [comment]
Great, thanks!
