### ISSUE TITLE
Provide pre-commit hook?

### ISSUE THREAD

**Issue by zmoon** [citation-file-format/cff-converter-python#268]
Looks like it wouldn't take much to [provide a pre-commit hook](https://pre-commit.com/#new-hooks) to run `--validate`.

**Comment by jspaaks** [comment]
Yes, that seems convenient for people to have. Are you planning to do more work on the PR? If not I can merge it as it is now. I like the `validate-cff` id BTW

**Comment by zmoon** [comment]
Yeah I think it is good to go. I tried it locally and it seemed to be working. My only concern was the sometimes-long error messages from jsonschema. I experimented with patching `jsonschema.exceptions._Error` to truncate the number of lines but not sure if you want to do that. And I guess that is a separate issue from this anyway.

**Comment by jspaaks** [comment]
OK great! I'm not worried about the long messages for now
