### ISSUE TITLE
cache spdx list of licenses

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#27]
the list you get here is what I mean:
https://github.com/citation-file-format/cff-converter-python/blob/aebaac1b61ce3594fde135d0385aeff1e2a61a96/cff_converter_python/citation.py#L199-L206

**Comment by sdruskat** [comment]
The current version of https://github.com/citation-file-format/schema/blob/master/CFF-Core/schema.yaml is bound to SPDX list 3.0, so you may want to consider using the blob permalink https://github.com/spdx/license-list-data/blob/b541ee8a345aa93b70a08765c7bf5e423bb4d558/json/licenses.json?

As opposed to referencing master, it will need work to maintain, but may be wort the trouble to stay aligned with the schema.

**Comment by jspaaks** [comment]
Updated the PR (76fa27c99ce5332b4eb6eac5ee1c4de8a4d4edf7)

**Comment by jspaaks** [comment]
wontfix the original problem. closing
