### ISSUE TITLE
Avoid printing the whole schema to the terminal when errors occur

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#278]
The useful information is usally at the top. Current workaround is piping the `stderr` into `stdout`, then `head`ing that:

```
cffconvert --validate 2>&1 | head -n 10
```

**Comment by nialov** [comment]
This should also be a priority for the `pre-commit` hook as currently the errors flood the screen with the schema. I would suggest adding a `--verbose` flag that would enable the full output (current) and by default shorten the message by truncating the `ValidationError` exception message.

**Comment by jspaaks** [comment]
Fixed by PR #290, closing this issue
