### ISSUE TITLE
License field in Zenodo export violates schema

### ISSUE THREAD

**Issue by sim642** [citation-file-format/cff-converter-python#279]
When converting `CITATION.cff` containing
```
license: MIT
```
to `.zenodo.json`, the resulting file contains
```json
"license": {
  "id": "MIT"
}
```

According to [Zenodo documentation about the file](https://developers.zenodo.org/?python#add-metadata-to-your-github-repository-release):
* [The human-readable documentation](https://developers.zenodo.org/#representation) says:
   
   > `license`
   > _string_

* [The linked JSON schema](https://zenodo.org/schemas/deposits/records/legacyrecord.json) specifies:

   ```json
   "license": {
     "description": "License for embargoed/open access content.",
     "title": "License",
     "type": "string",
     "default": "CC-BY-4.0"
   }
   ```

According to both, it should be
```json
"license": "MIT"
```

**Comment by sim642** [comment]
I suppose that's why it was implemented as an object here, but it might not be wise to depend on some undocumented behavior.

**Comment by jspaaks** [comment]
In principle I agree but there is some discussion how (if) the published schemas are used, e.g.

https://github.com/zenodo/zenodo/issues/2294#issue-1148049228

And additionally some people start their metadata from downloading the JSON for an existing record, which shows e.g.:

![image](https://user-images.githubusercontent.com/4558105/184191484-1392094c-3e92-4e87-a791-6efff66e1bca.png)

So, a bit of a conundrum I guess
