### ISSUE TITLE
Regarding a tool that derives citation file from pyproject.toml (PEP-621)

### ISSUE THREAD

**Issue by funkyfuture** [citation-file-format/cff-converter-python#282]
i came up with the idea that for Python projects it would be less effort to maintain metadata if a citation file would be derived from a `pyproject.toml` that includes metadata according to [PEP-621](https://peps.python.org/pep-0621/). i *might* at some point in the future want to address this. would you be interested to include such functionality as subcommand here, or shall it rather live in an extra Python package?

**Comment by jspaaks** [comment]
Hi @funkyfuture, thanks for contributing the idea! I think such functionality would probably be most at home as a separate package

**Comment by funkyfuture** [comment]
thanks for pointing me there!
