### ISSUE TITLE
Accept X in last position of Orcid

### ISSUE THREAD

**Issue by orichters** [citation-file-format/cff-converter-python#394]
The Orcid format can have an `X` meaning 10 in the last position as this is a check digit, see https://en.wikipedia.org/wiki/ORCID#Identifiers or https://orcid.org/0000-0002-9079-593X

I guess that [these patterns](https://github.com/search?q=repo%3Acitation-file-format%2Fcffconvert%20%5B0-9%5D%7B4%7D-%5B0-9%5D%7B4%7D-%5B0-9%5D%7B4%7D-%5B0-9%5D%7B4%7D&type=code) would need to be adjusted to `"https://orcid\\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]"`

It seems there has been a debate before about that, with [removing an author with this feature from the tests](https://github.com/citation-file-format/cffconvert/pull/328), so I don't know whether that is a design choice, but at least it leads to the situation that I cannot use your software because validation fails.

**Comment by jspaaks** [comment]
Hi @orichters, thanks for making the issue. What version of `cffconvert` are you using, and could you provide a link to your `CITATION.cff` so I can have a look?

**Comment by orichters** [comment]
Dear @jspaaks, thanks for your quick reply and sorry for not providing sufficient information.

I'm using a fresh install of `cffconvert 2.0.0`.

But: I just realized that indeed you already adjusted the orcid pattern from cff-version 1.1.0 on, see [for example here](https://github.com/citation-file-format/cffconvert/blob/b6045d78aac9e02b039703b030588d54d53262ac/src/cffconvert/schemas/1.1.0/schema.yaml#L179). So adjusting the `cff-version` from `1.0.3` to `1.2.0` in my `CITATION.cff` solved my problem.

Sorry for bothering you, have a nice day, and thanks for your software.

**Comment by jspaaks** [comment]
No problem, glad to hear you made it work!
