### ISSUE TITLE
Automatically replace 'YourReferenceHere' with author-name and year where possible. 

### ISSUE THREAD

**Issue by NiklasMelton** [citation-file-format/cff-converter-python#395]
YourReferenceHere seems to be hard-coded on this line:
https://github.com/citation-file-format/cffconvert/blob/b6045d78aac9e02b039703b030588d54d53262ac/src/cffconvert/lib/cff_1_x_x/bibtex.py#L31

It would be better to replace this with something like:

```
try:
    ref_alias = self.author[10:].replace(" and ",", ").split(",")[0] + self.year[10:12]
except:
    ref_alias = "YourReferenceHere"
return "@misc{"+ref_alias+",\n" + joined + "\n}\n"
```

**Comment by jspaaks** [comment]
Hi Nik, thanks for making this issue. I don't think there is a way to automatically create the label such that it fits everybody's preferred way, hence I'm choosing to leave it as-is. However, a reference manager might be able to do what you want, see for example here https://docs.jabref.org/setup/citationkeypatterns
