### ISSUE TITLE
doi: null in zenodo export

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#57]
when i do:

```bash
cffconvert -f zenodo --url https://github.com/ERA-URBAN/netcdf2littler/tree/6adc6f1c3839937b66dd33d3655ab0b92b396c24
```
I get a null value for doi:
```bash
Note: suspect keys will be included in the output.
{
    "creators": [
        {
            "affiliation": "Netherlands eScience Center",
            "name": "van Haren, Ronald"
        }
    ],
    "doi": null,
    "keywords": [
        "WRF",
        "WRFDA",
        "LITTLE_R",
        "netCDF"
    ],
    "license": {
        "id": "Apache-2.0"
    },
    "publication_date": "2018-05-31",
    "title": "netcdf2littler",
    "version": "1.0.0"
}
```

and similar for codemeta export.

**Comment by rvanharen** [comment]
Should I first make a release and at the doi and such to the citation file?

**Comment by jspaaks** [comment]
Not necessarily, the validator gives no errors:

```bash
cffconvert --url https://github.com/ERA-URBAN/netcdf2littler/tree/6adc6f1c3839937b66dd33d3655ab0b92b396c24 --validate
```
Because the CITATION.cff is part of the release, there is a chicken-and-egg problem. To avoid this, I would 
- use Zenodo-GitHub integration (otherwise you won't see much on research-software.nl, and it's the easiest way to make releases anyway).
- regarding the CITATION.cff file, 
    - omit any ``commit`` information (because the commit sha changes as soon as you commit it).
    - use the concept doi as ``doi`` from the CITATION.cff (this implies you need at least one release, probably the easiest way to do that is by making a prerelease 1.0.0-rc1 or something)
    - manually add the release date as ``date-released`` (this is required to pass validation)
    - manually add the version number as ``version``

Once you have that, run
```bash
# Install the cffconvert tool
pip install cffconvert

# Check if the CITATION.cff file found in the current directory is valid CFF (BTW I noticed
# this still generates local files 'data.yaml' and 'schema.yaml'; this is a bug. Just remove
# them).
cffconvert --validate

# If the file is valid, generate the ``.zenodo.json`` metadata file (note the dot in the filename).
# Note that I'm omitting the ``commit``, ``date-released``, and ``doi`` keys by including the 
# ``--ignore-suspect-keys`` flag. This is because it's better/less error prone to let the
# GitHub-Zenodo integration take care of those metadata.
cffconvert --outfile .zenodo.json --outputformat zenodo --ignore-suspect-keys

# don't forget to add, commit and push the new file
git add .zenodo.json
git commit -m "added Zenodo metadata file"
git push somewhere
```

Optionally, you can also generate a ``codemeta.json`` (no dot here) file with rich metadata that search engines may pick up (although I don't think they do at the moment, at least not from within GitHub repos).

```bash
cffconvert --outfile codemeta.json --outputformat codemeta

# don't forget to add comiit and push the new file
git add codemeta.json
git commit -m "added codemeta metadata file"
git push somewhere
```

Hope this helps, let me know if you run into trouble,
-Jurriaan

**Comment by jspaaks** [comment]
Not sure this is still a problem, this code (https://github.com/citation-file-format/cff-converter-python/blob/435b6e98ac91eb560bc7e4f43cbf55640b76dbab/cffconvert/citation.py#L469-L470) suggests it may have been resolved.

**Comment by jspaaks** [comment]
Confirmed fixed in https://github.com/citation-file-format/cff-converter-python/tree/45097401de7473ba54ef0053c9a37d56c7af8f23, closing.
