### ISSUE TITLE
zenodo export orcid identifier should maybe not include https://orcid.org part?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#73]
zenodo says "Not a valid orcid identifier" when I made a release of this repo, with this orcid in its .zenodo.json:

https://github.com/citation-file-format/cff-converter-python/blob/79a216efd792acbb715222838244b0979961687c/.zenodo.json#L18

here the complete error from https://zenodo.org/account/settings/github/repository/citation-file-format/cff-converter-python:

```json
{
    "status": 400, 
    "message": "Validation error.", 
    "errors": [
        {
            "field": "metadata.creators.3.orcid", 
            "message": "Not a valid ORCID identifier."
        }
    ]
}
```

**Comment by jspaaks** [comment]
fixed, e.g. https://zenodo.org/record/1421832#.W6On3xRoRzg

**Comment by vincentvanhees** [comment]
hi Jurriaan, what was the fix you used for this? I just noticed that I have this bug too and it stops zenodo from creating dois for new releases.

**Comment by jspaaks** [comment]
BTW I updated the guide with some notes on newly available tooling to generate CFF, convert to .zenodo.json etc.
https://github.com/NLeSC/guide/blob/8675c9a45fdc9da38d37d24e7e4f420cd159342f/citable_software/making_software_citable.md

**Comment by sdruskat** [comment]
Thanks @jspaaks for reminding me of the bug in the schema, will prepare a new release with the fix.
