### ISSUE TITLE
UnsafeLoaderWarning warning

### ISSUE THREAD

**Issue by thomaskrause** [citation-file-format/cff-converter-python#89]
Whenever I run cffconvert, it will output a warning about an unsafe YAML loader:
```
$ cffconvert --validate -if CITATION.cff 
/home/thomas/.local/lib/python3.6/site-packages/pykwalifire/core.py:91: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  self.source = yaml.load(stream)
```
Python version is 3.6.7, OS is Ubuntu 18.10

**Comment by jspaaks** [comment]
Hey 
thanks for the bug report. I'll try to look into it ASAP. For reference, what does
```
cffconvert --version
```
return?

**Comment by thomaskrause** [comment]
Hi,

its reports the latest version 1.0.4.

pykwalifire also reports the newest version 2.0.1
```
$ pip3 show pykwalifire
Name: pykwalifire
Version: 2.0.1
Summary: Python lib/cli for JSON/YAML schema validation, fork of pykwalify with added features
Home-page: http://github.com/sdruskat/pykwalifire
Author: Stephan Druskat
Author-email: mail@sdruskat.net
License: MIT
Location: /home/thomas/.local/lib/python3.6/site-packages
Requires: python-dateutil, PyYAML, ruamel.yaml, docopt
```

**Comment by jspaaks** [comment]
I'm having some difficulty reproducing this bug despite being on the same OS with the same ``cffconvert`` version and python version.

Could you please try installing ``cffconvert`` in a clean virtual environment following the steps below?

```
# change to a temp dir
cd $(mktemp -d)

# make a virtual environment
# (I think I installed virtualenv with 'sudo apt install python-virtualenv')
virtualenv -p /usr/bin/python3 venv3

# activate the virtual environment
source venv3/bin/activate

# install cffconvert from PyPI
pip install cffconvert

#see if it makes a difference
cffconvert --validate -if CITATION.cff
```

I'd also be interested in the CITATION.cff file contents, maybe something there triggers some unexpected behavior?

**Comment by thomaskrause** [comment]
I can't reproduce this in a virtual environment either. It seems like I had an older version of the ruamel.yaml package installed. There was a folder in `~/.local/lib/python3.6/site-packages/` for each version, but also a shared (?) folder `~/.local/lib/python3.6/site-packages/ruamel` without any version information at all. After deleting this folder and and re-installing cffconvert the warning is gone.

**Comment by jspaaks** [comment]
Pfew I'm glad! I was kind of running out of ideas :)
