### ISSUE TITLE
verify PyYAML 1.2 support

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#9]
https://pypi.python.org/pypi/pykwalifire/2.0.1

**Comment by jspaaks** [comment]
not sure what i wanted with this. closing for now.

**Comment by sdruskat** [comment]
I think this could be related to PyYAML not supporting YAML 1.2 as of yet, while pykwalifire does? 

The "true superset of JSON" quality of YAML had been introduced with YAML 1.2, but I haven't checked whether this is relevant at all to the implementation of CFF, so could be a theoretical problem.

**Comment by jspaaks** [comment]
Hey Stephan,
I think the original angle had something to do with clashing yaml parsers ruamel v pyyaml. I propose to let this issue remain closed until we know what the issue is :)

off topic but I wonder if you should be in here https://github.com/citation-file-format/cff-converter-python/blob/797ec158070814b6694a764fe79f6110ddb64f18/CITATION.cff#L3-L15

**Comment by sdruskat** [comment]
Yea, the clashing parsers / 1.2 support is why pykwalifire has ruamel as default.

I'd be honoured to be in the CFF file, thanks!

And while we're off-topic, I think it'd be awesome if you or any of your team could take part in the [CFF hack day at RSE18](https://citation-file-format.github.io/events/rse18-hack-day/)! You're definitely one of the most active developers for CFF tooling, so it'd be great to have you there!

**Comment by jspaaks** [comment]
just registered for RSE2018 and hackday. See you there!

**Comment by sdruskat** [comment]
Excellent! See you there indeed!
