### ISSUE TITLE
Mention web service in README

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/cff-converter-python#91]
The README should mention the available web service at some point, at least if it's stable (and perhaps has a more accessible URL).

**Comment by sdruskat** [comment]
https://us-central1-citation-cff.cloudfunctions.net/convert?url=https://github.com/NLeSC/spot&format=bibtex 

At the time of writing, this throws:

```
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /NLeSC/spot/master/CITATION.cff (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2b39000a0b38>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

cc @jspaaks

**Comment by Tommos0** [comment]
I've setup the webservice several months ago, mostly to show that this is a possibility. It hasn't been updated since, so the error might already be fixed with the latest code.

If we really are going to support this endpoint, someone should be responsible for maintaining it (we can probably simplify this by setting up an automatic deployment from the latest master branch).

I suggest we don't make it public until that's taken care of.

**Comment by jspaaks** [comment]
I did some digging in the Google Cloud Function logs. There are many instances of billing account errors there. Maybe we exceeded some kind of limit?
I agree with @Tommos0 though on support and doing things a bit more properly.

**Comment by jspaaks** [comment]
I finally managed to find the button "Enable billing" in Google's Cloud function admin thingy. Clicked it, now it works again. I wonder where the bill ends up though...?

**Comment by Tommos0** [comment]
I cannot see the `billing account`, so I think the billing account is now linked to your google account. You get 300EUR or so for free at Google cloud, it's probably running on this now.

**Comment by Tommos0** [comment]
https://cloud.google.com/functions/pricing

**Comment by Tommos0** [comment]
https://cloud.google.com/community/tutorials/cloud-functions-github-auto-deployer
https://github.com/citation-file-format/cff-converter-python/commit/a10779e5d5cb01c69eed900044714fc09ac0f088

**Comment by jspaaks** [comment]
readme updated https://github.com/citation-file-format/cff-converter-python/pull/98
