### ISSUE TITLE
Hard dependency on exact version numbers

### ISSUE THREAD

**Issue by rowleya** [citation-file-format/cff-converter-python#95]
The hard dependency on exact version numbers makes this difficult to use.  Would it be possible to use more soft requirements e.g. >= or if semantic versioning is supported by the dependency, use that instead e.g. 
```
requests >= 2.20.0, < 3.0.0
```

**Comment by jspaaks** [comment]
Let me know if [1.2.1](https://pypi.org/project/cffconvert/1.2.1/) doesn't solve your problem
